### ISSUE TITLE
Does it work with 19.04?

### ISSUE THREAD

**Issue by vivekjib** [rajatgupta1998/kernel_hp-15ac126tx_i5-5200U#1]
There is an upgrade to Ubuntu which uses kernel version 5. Please, check its viability with that.

**Comment by rajatgupta1998** [comment]
> There is an upgrade to Ubuntu which uses kernel version 5. Please, check its viability with that.

Yes, I will create a branch for ubuntu's kernel which they ship on 19.04 and another one with kernel.org's 5.x branch. I use Disco Dingo on my server so yeah, will create a branch. However a custom driver is no longer required in new releases  of 4.19 and higher atleast for some people including me. Thanks.
